name: alerts
description: "OnAlert: Full-Stack IoT Accident Detection System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  video_player: ^2.8.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  firebase_auth: ^4.18.0
  cloud_firestore: ^4.17.0
  firebase_database: ^10.5.7
  firebase_messaging: ^14.9.0

  google_maps_flutter: ^2.14.2
  geolocator: ^11.1.0

  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  vibration: ^2.0.0
  sensors_plus: ^5.0.1
  google_sign_in: ^7.2.0
  chewie: ^1.8.1

  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  share_plus: ^7.2.2
  pdf: ^3.11.1
  path_provider: ^2.1.4
  mobile_scanner: ^5.2.3
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/splash_video.mp4
    - assets/videos/tut1.mp4
